EVENT_TYPE_PERSON = "보행자 감지"
EVENT_TYPE_VEHICLE = "차량 감지"
EVENT_TYPE_CONGESTION = "정체 의심"
EVENT_TYPE_STOPPED_VEHICLE = "정지 차량 의심"

RISK_LOW = "낮음"
RISK_WARNING = "주의"
RISK_DANGER = "위험"
RISK_EMERGENCY = "긴급"